def addition(a:int,b:int,c:int):
    return a+b+c
def subtraction(a:int,b:int,c:int):
    return a-b-c
def multiply(a,b):
    return a*b
def division(a,b):
    return a/b;
def modulus(a,b):
    return a%b
def max(a,b,c):
    return max(a,b,c)
